### ISSUE TITLE
tab-custom-icon.directive.js error

### ISSUE THREAD

**Issue by januff** [GerritErpenstein/ionic2-custom-icons#1]
Thanks for this crucial plug-in, Gerrit! 

Got the custom-icon directive working perfectly, but on both my project and a local copy of your Example app, the tab-custom-icon directive is failing to display the icon, throwing errors like so:

tab-custom-icon.directive.js:127 
Uncaught TypeError: Cannot set property 'className' of undefined
TabCustomIcon._update @ tab-custom-icon.directive.js:127
(anonymous function) @ tab-custom-icon.directive.js:48
ZoneDelegate.invokeTask @ zone.js:356
onInvokeTask @ ng_zone_impl.js:44
ZoneDelegate.invokeTask @ zone.js:355
Zone.runTask @ zone.js:256Z
oneTask.invoke @ zone.js:423

tab-custom-icon.directive.js:93 
No ion-tabbar node at index 0.

Any ideas?

**Comment by GerritErpenstein** [comment]
Hi januff, thanks for the issue report!
This could be a problem/incompatibility with the new version 2.0.0-beta.11 of Ionic. Give me a day or two for adapting the library. I will get back to you asap.

**Comment by GerritErpenstein** [comment]
The problem should be fixed in version 0.2.1. Please report back otherwise. Thanks!

**Comment by januff** [comment]
Works like a charm. You rock, Gerrit.
