### ISSUE TITLE
custom icons appear smaller than ionicons

### ISSUE THREAD

**Issue by YasirPanjsheri** [GerritErpenstein/ionic2-custom-icons#10]
Hi , I have followed the instructions and set up everything, its working fine but however the icons appear in smaller size, how to fix this issue ??

![screenshot from 2017-01-11 15-59-43](https://cloud.githubusercontent.com/assets/12644122/21846978/2c5abc76-d817-11e6-97a0-970c9aba2c27.png)

the screenshot above , on the right is ionicon , on left is EvilIcons

.html

     <custom-icon set="ei" name="chevron-right" item-right></custom-icon>
      <ion-icon name="ios-arrow-forward" item-right></ion-icon>

**Comment by GerritErpenstein** [comment]
You're right, this looks a bit off. :wink: I will look into it!

**Comment by YasirPanjsheri** [comment]
Hi mr.Gerrit , any updates regarding this issue ?

**Comment by GerritErpenstein** [comment]
Actually yes. The size of the icons seems to be correct. The arrow icon of EvilIcons is just smaller than the Ionicon one. I will post a screenshot later...

**Comment by GerritErpenstein** [comment]
I have imported the original Ionicon icon pack using the library and created a custom icon set. See the following screenshot:
![screenshot_20170118_081951](https://cloud.githubusercontent.com/assets/9967761/22215647/6ab988c4-e19c-11e6-9b93-1396a3fa1e6c.png)
The left icon is inserted using the `ion-icon` directive (marked with an "I"), the right one using the `custom-icon` directive (marked with a "C"). As you can see, they both have the same size.

However both icons don't seem to be in line. But that is another problem I will look into.

**Comment by YasirPanjsheri** [comment]
can you provide a link for original icon packs ?

**Comment by GerritErpenstein** [comment]
Sorry for the late response. I must have missed your message.
You can find the original Ionicon svgs here: https://github.com/driftyco/ionicons/tree/3.0

I'm not sure if I completely understand your problem. Ionicons, Evil Icons and Foundation Icons are different icon sets. Although there are icons that are similar, they don't necessarily have the same size.

The a look at both icons you mentioned:

- https://github.com/evil-icons/evil-icons/blob/master/assets/icons/ei-chevron-right.svg
- https://github.com/driftyco/ionicons/blob/3.0/src/ios-arrow-forward.svg

You can clearly see that the first one (Evil Icons set) is much smaller. This library does not change the icon's proportions.

**Comment by GerritErpenstein** [comment]
As there aren't any more comments or questions I'm closing this issue.
