### ISSUE TITLE
Issue with heroku deploy

### ISSUE THREAD

**Issue by sagivf** [GerritErpenstein/ionic2-custom-icons#13]
Hey,

A bit of an edge case, but i'm trying to get this deploying on heroku and something isn't working.
Runnig `npm run ionic2-custom-icons` locally on a mac I get:
```
[14:30:58] ionic2-custom-icons: Creating custom icon set 'spikli'
[14:30:59] gulp-svgicons2svgfont: Font created
ionic2-custom-icons: Successfully created icons
```

But on Heroku I get
```
 [12:29:55] ionic2-custom-icons: Creating custom icon set 'spikli'
 ionic2-custom-icons: Successfully created icons
.
.
.
  [12:30:27]  sass: .tmp-custom-icons/scss/variables.scss, line: 1
File to import not found or unreadable: ionic2-custom-icons Parent style sheet:
  /tmp/build_a0a98ac9dc06443aac60baec800ed748/.tmp-custom-icons/scss/variables.scss
```
Seems like `gulp-svgicons2svgfont` isn't being called or failing but no clear message. Any idea if there might be a dependency missing or any advice?

**Comment by GerritErpenstein** [comment]
Damn, just realised installing the library without a version number resolves to `0.4.1-beta.0`. That could be the case for you. Can you please check that your `package.json` statically sets the version number to `0.3.1`?
```
"dependencies": {
     ...
     "ionic2-custom-icons": "0.3.1",
     ...
}
```

**Comment by GerritErpenstein** [comment]
Forgot to add the beta tag to the release. Please update/reinstall your node modules. That should fix the error. Sorry for the inconvenience.

**Comment by sagivf** [comment]
@GerritErpenstein I think it's ok, running `npm install ionic2-custom-icons --save` results in `"ionic2-custom-icons": "^0.3.1"`.
 I tried installing `0.4.1-beta` to see if it helps with my issue...

**Comment by sagivf** [comment]
But both fail on heroku.

**Comment by GerritErpenstein** [comment]
I have never used Heroku but let me see if I can set up a simple project to reproduce the error.

**Comment by sagivf** [comment]
@GerritErpenstein Thanks, I know this is kind of out of scope but I thought I'd give it a shot... it's probably either something to do with paths or something to do with herokus file accesses. 

Do you want me to open a project to reproduce and share it with you?
Only if you have the time and patience for this of course...

**Comment by sagivf** [comment]
Ive found that I can just commit the generated font / scss folders. Not ideal but not critiacal at all so I'm gonna close this.
