### ISSUE TITLE
Icon's original color

### ISSUE THREAD

**Issue by juanshot** [GerritErpenstein/ionic2-custom-icons#14]
Hi!  i imported flags icons set  and it works great but i need to see the original flags color not outline. how do i do that? thanks!

**Comment by GerritErpenstein** [comment]
Hi! I'm not quite sure if I understand the problem. Can you point me to the mentioned icon set or give me an example?

**Comment by juanshot** [comment]
ok. Im using svg full color flags and it already works i already use it
 like this:

<custom-icon set="fl" name="united-states" item-right ></custom-icon>

but it outputs an united states image black & white.  is there any way to
show the original colors of my image?


2017-02-06 12:14 GMT-05:00 Gerrit Erpenstein <notifications@github.com>:

**Comment by GerritErpenstein** [comment]
The icons are converted to a "normal" font set. Fonts are monochrome which means there is only one color. This is by design and there is not much I can do about it.
If you need colored icons, use SVGs (make sure your target platforms support SVGs) or use PNGs.
Thanks for your request!
