### ISSUE TITLE
Can't color icons used in tabs

### ISSUE THREAD

**Issue by twilliamsgsnetx** [GerritErpenstein/ionic2-custom-icons#15]
I have added these custom icons to my tabs, using the following css.

```
    .ion-ios-executive,
    .ion-md-executive,
    .ion-wp-executive {
        content: url(../../assets/imgs/executive.svg);
    }
```

Nothing I seem to do at this point allows me to custom color these icons, when used as icons for tabs in Ionic 2. Any thoughts?

**Comment by mwiley63** [comment]
I can confirm that colors work in Ionic 3.x by setting Ionic's sass variables like so:
```
$tabs-ios-tab-icon-color-active: map-get($colors, my-brand-color);
$tabs-md-tab-icon-color-active: map-get($colors, my-brand-color);
```

Note, this also worked for me using a non-primary color in versions < 3.x with ionicons.

**Comment by luiz-c** [comment]
Hi, I'm new to ionic and to this custom icon stuff. I just wanna know if its possible for the SVG to keep its color instead of getting from the sass variables. Because I have one icon that has around 5 colors and when I put in the ionic tab it stays in grey. Thanks.

**Comment by srijanDubey** [comment]
Hi @luiz-c,

were you able to achieve that. Keeping svg's pre filled colors. I want achieve the same for my application.
