### ISSUE TITLE
Custom Icons for ActionScreenController

### ISSUE THREAD

**Issue by ThorvaldAagaard** [GerritErpenstein/ionic2-custom-icons#19]
Hi Gerrit

I like the way you have implemented Custom Icons for Tabs, but have you found a way I can use you Custom icons for a ActionSheet, or am I left with the buildt in icons?

    let profilePicSheet = this.actionSheetCtrl.create({
      title: 'Upload your Picture',
      buttons: [
        {
          text: 'Take a Picture',
          role: 'destructive',
          icon: !this.platform.is('ios') ? 'camera' : null,
          handler: () => {
            this.getPicture(true);
          }
        }, {
          text: 'Cancel',
          role: 'cancel',
          icon: !this.platform.is('ios') ? 'close' : null,
          handler: () => {
          }
        }
      ]
    });
    profilePicSheet.present();

It seems like Ios is not supporting icons at all, and currently only the ionicicons can be used for other platforms

**Comment by GerritErpenstein** [comment]
Hi Thorvald!
I will look into adding icons to Action Sheets as soon the current beta has been released as a stable version. I hope to have some time tomorrow.
Thanks for the feature request!

**Comment by ThorvaldAagaard** [comment]
Sounds great. Will I have to upgrade to Ionic CLI 3.0 to test the beta version ?

**Comment by GerritErpenstein** [comment]
No, you actually have to stay with `ionic-cli 2.x` right now.
See here for more info: [README-BETA.md#warning-ionic-cli-300-betax-incompatible](https://github.com/GerritErpenstein/ionic2-custom-icons/blob/master/README-BETA.md#warning-ionic-cli-300-betax-incompatible)

**Comment by ThorvaldAagaard** [comment]
Ok, I will stay on ionic-cli 2.2.0 for now.

I you should manage to implement the feature for ActionSheet, what will then be the requirements for my app? I can see the beta refers to Angular 4, and due to missing upgrade of AngularFire I am currently stuck at Ionic version 2

**Comment by GerritErpenstein** [comment]
The beta and succeeding stable release might work with Ionic 2.x. Just give it a try!

**Comment by GerritErpenstein** [comment]
I have a working prototype for adding custom icons to Action Sheet buttons. This one was a bit tricky as Ionic wasn't really developed with extending its core functionality in mind.
Give me a few days to clean up and test the code...

**Comment by GerritErpenstein** [comment]
Stable release in version 0.5.0.
