### ISSUE TITLE
Support Ionic 2.0.0-rc.0

### ISSUE THREAD

**Issue by GerritErpenstein** [GerritErpenstein/ionic2-custom-icons#2]
- [x] Switch from gulp to npm build system
- [x] Fix tabs directive
- [x] Update README
- [ ] ...?

**Comment by GerritErpenstein** [comment]
A new version for Ionic 2.0.0-rc.0 will be available tomorrow. I am just making finishing touches.

**Comment by sagivf** [comment]
Thanks @GerritErpenstein, way to push through a major set back!

**Comment by januff** [comment]
Working for me, really nice job.
