### ISSUE TITLE
hello build error with ionic 3.3.0

### ISSUE THREAD

**Issue by jmickvs** [GerritErpenstein/ionic2-custom-icons#20]
Hello I have a trouble with ionic 3.3.0 and custom-icons plugin 0.4.1 when build the project, I got the next error 

>17:25:59]  ngc finished in 14.84 s 

> [17:25:59]  preprocess started ... 
> [17:25:59]  deeplinks started ... 
> [17:26:00]  deeplinks finished in 1.02 s 
> [17:26:00]  preprocess finished in 1.02 s 
> [17:26:00]  webpack started ... 
> [17:26:00]  copy finished in 16.10 s 
> [17:26:35]  webpack finished in 35.29 s 
> [17:26:35]  sass started ... 
> [17:26:35]  sass: stdin, line: 1 
>             File to import not found or unreadable: .tmp-custom-icons/scss/variables.scss. Parent style sheet: stdin 
> 
> [WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of date.
> Error: Failed to render sass to css

this error also got it when I work with ionic 3.0.1, i dont know what is the problem i hope you can help me

ionic info
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.6.0
    OS         : Linux 3.16
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

regards.

**Comment by GerritErpenstein** [comment]
Hi @jmickvs ,
currently this library does not work with `ionic-cli 3.x`. Please see the corresponding issue #18 for more info.
