### ISSUE TITLE
ionic2-custom-icons / Android Kitkat

### ISSUE THREAD

**Issue by ymmedia** [GerritErpenstein/ionic2-custom-icons#21]
Hello,

How does ionic2-custom-icons work if the system (android kitkat) does not support svg ?

Thank you in advance for your answer

Medjay.

**Comment by GerritErpenstein** [comment]
Hey @ymmedia,
as stated in the docs:

> The npm-script allows creating icon fonts from a given set of SVG vector images during the app's build phase.

This means the library does not embed SVGs in the app. Instead it converts your SVGs into fonts, that all browsers support.
BTW I'm pretty sure KitKat's internal browser runtime supports SVGs.

**Comment by ymmedia** [comment]
thank you for your reply
