### ISSUE TITLE
File : 'tmp-custom-icons/scss/variables.scss' not found

### ISSUE THREAD

**Issue by Hexagoo** [GerritErpenstein/ionic2-custom-icons#24]
Hey everyone!
I'm using ionic2-custom-icons in order to animate my customs SVG in my Ionic App.
This error dropped after installation:

`File to import not found or unreadable: .tmp-custom-icons/scss/variables.scss. Parent style sheet: stdin`

Someone has an idear?

**Comment by GerritErpenstein** [comment]
Hi @Hexagoo 
Please verify the example app works for you: https://github.com/GerritErpenstein/ionic2-custom-icons-example

**Comment by Hexagoo** [comment]
Hey @GerritErpenstein thanks for the answer!
It dropped exactly the same error after running ionic2-custom-icons-example on my computer :/

**Comment by GerritErpenstein** [comment]
Mmmh weird. Can you please post the output of `ionic info` from within your project directory?

**Comment by Hexagoo** [comment]
Yeeees

`@ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.9.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
`

**Comment by Hexagoo** [comment]
Yeeeees

    ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:

    ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node       : v6.9.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by GerritErpenstein** [comment]
You are using an old version of `ionic cli`. Please update to the latest version `3.7.0`.

**Comment by Hexagoo** [comment]
Oooh thanks you! It works...
Command : `sudo npm install -g ionic@latest`

**Comment by utpaul** [comment]
Hi i got same problem but hare i am using ` "ionic-angular": "3.9.5"` and  `"@ionic/app-scripts": "3.2.2"`  @GerritErpenstein .

I also try [ionic2-custom-icons-example](https://github.com/GerritErpenstein/ionic2-custom-icons-example) but not luck.

**My machine ionic info:**

`Ionic:

   ionic (Ionic CLI) : 4.12.0

System:

   NodeJS : v11.6.0
   npm    : 6.8.0
   OS     : Windows 10`

**Project info:**

 Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\DEV-2\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

System:

   NodeJS : v11.6.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.8.0
   OS     : Windows 10
