### ISSUE TITLE
Icons not displaying on tabs Ionic 3.8.1

### ISSUE THREAD

**Issue by zimnerd** [GerritErpenstein/ionic2-custom-icons#26]
HERE is the code 

<ion-tabs id="tabs-tabs1" selectedIndex="1">
  <ion-tab [root]="tab1Root" tabTitle="Submit Claim" tabIcon="checkmark-circle" id="tabs-tab1"></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="Menu" tabIcon="menu" id="tabs-tab4"></ion-tab>
  <ion-tab [root]="tab3Root" tabTitle="Balances"  set="defy" name="wallet-balance-white"></ion-tab>
  <ion-tab [root]="tab4Root" tabTitle="Support" customIconSet="defy" customIconName="support-white" id="tabs-tab3"></ion-tab>
</ion-tabs>
```

**Comment by GerritErpenstein** [comment]
The icons in tabs are still working for me with `ionic-cli 3.8.1`. Please compare your code with the example app: https://github.com/GerritErpenstein/ionic2-custom-icons-example
Feel free to reopen the issue if have you can provide more information.

**Comment by zimnerd** [comment]
@GerritErpenstein , The icons are now working, I think the issue was with the SVG files. Do you have any idea how to maintain the svn icon colors because they are only being displayed as a solid color.

Thanks
