### ISSUE TITLE
 ionic2-custom-icons-example@ ionic:watch:before: `ionic2-custom-icons`  Exit status 1

### ISSUE THREAD

**Issue by charly7carlos** [GerritErpenstein/ionic2-custom-icons#27]
> cli packages: (D:\ionic\nofunciona\node_modules)
> 
>     @ionic/cli-utils  : 1.9.2
>     ionic (Ionic CLI) : 3.9.2
> 
> global packages:
> 
>     Cordova CLI : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 2.1.4
>     Cordova Platforms  : none
>     Ionic Framework    : ionic-angular 3.6.1
> 
> System:
> 
>     Android SDK Tools : 26.1.1
>     Node              : v6.11.3
>     npm               : 5.4.2
>     OS                : Windows 10

`D:\ionic\nofunciona>ionic serve
> npm run ionic:watch:before

> ionic2-custom-icons-example@ ionic:watch:before D:\ionic\nofunciona
> ionic2-custom-icons

"ionic2-custom-icons" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic2-custom-icons-example@ ionic:watch:before: `ionic2-custom-icons`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic2-custom-icons-example@ ionic:watch:before script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2017-09-23T22_08_12_780Z-debug.log
[ERROR] An error occurred while running npm run ionic:watch:before (exit code 1).

`

package.json

 "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic2-custom-icons": "ionic2-custom-icons",
    "ionic:watch:before": "ionic2-custom-icons",
    "ionic:build:before": "ionic2-custom-icons",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },

**Comment by GerritErpenstein** [comment]
Hi @charly7carlos!
Sorry, I have forgotten to answer you after returning from holidays. Did you manage to resolve the problem yourself?
I'm not really sure what causes this error. Please provide the output in english and attach the mentioned debug log file.
Thank you.

**Comment by tenglandct** [comment]
My Portuguese (I think??) isn't very good but I believe I was having the same issue. I was previously running npm 5.3.0 and upgrading to npm 5.5.1 fixed the issue for me.

**Comment by GerritErpenstein** [comment]
I can't even run ionic with such an old npm version:
```
#ionic serve
ERR: Your Node.js version is v5.4.1. Please update to the latest Node 6 LTS or Node 8 LTS.
```
Please update to a newer version and see if it works. I'm closing this issue meanwhile. If updating npm doesn't fix your problem, feel free to reopen the issue.
