### ISSUE TITLE
Icon in Item of a List

### ISSUE THREAD

**Issue by marcogrieco** [GerritErpenstein/ionic2-custom-icons#28]
Hi,
if i use the custom icon as icon in an item of a list the text on the right is not vertically aligned.

Here the piece of my code
```
<ion-item menuClose *ngFor="let p of pages" (click)="openPage(p)">
        <custom-icon set="myIcons" name="bitcoin" item-start></custom-icon>
        {{p.title | translate}}
</ion-item>
```

Thanks in advance.

Marco

**Comment by GerritErpenstein** [comment]
Hi @marcogrieco,
I have tested your piece of code but can not confirm your findings. Can you please provide more example code and a screenshot? Thanks

**Comment by marcogrieco** [comment]
![alignment](https://user-images.githubusercontent.com/26677763/32828100-8546bc58-c9ee-11e7-95fa-6db10499df69.png)

**Comment by GerritErpenstein** [comment]
I am still unable to reproduce the issue. See the following screenshot that is similar to your example:
![screenshot_20171115_201507](https://user-images.githubusercontent.com/9967761/32855509-2571ceae-ca42-11e7-81f7-90303c25866d.png)
My code is based on the [example app](https://github.com/GerritErpenstein/ionic2-custom-icons-example). I have changed the file `src/app/app.html` to adapt your use case:
```
<ion-menu [content]="content">
  <ion-content>
    <ion-list>
      <ion-list-header>
        Examples
      </ion-list-header>
      <button menuClose ion-item *ngFor="let p of pages" (click)="openPage(p)">
         <custom-icon set="foundation" name="home" item-start></custom-icon>
        {{p.title}}
      </button>
    </ion-list>
  </ion-content>
</ion-menu>

<!-- Disable swipe-to-go-back because it's poor UX to combine STGB with side menus -->
<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
```
Using `<ion-item>` instead of `<button>` leads to the same result.

I'm afraid there is not much I can do without more extensive example code.

**Comment by marcogrieco** [comment]
This is the code html of my page

```
<ion-menu [content]="content">
  <ion-header>
    <ion-toolbar color="primary">
      <ion-title padding-left>{{'LABELS.MENU' | translate}}</ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-content>
    <ion-list>
      <ion-item no-lines class="bottom-border" menuClose *ngFor="let p of pages" (click)="openPage(p)">
        <custom-icon set="myIcons" name="{{p.icon}}" margin-right item-start></custom-icon>
        {{p.title | translate}}
      </ion-item>
    </ion-list>
  </ion-content>
</ion-menu>

<!-- Disable swipe-to-go-back because it's poor UX to combine STGB with side menus -->
<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
```
I have attached one of the icons that i use in the menu.

The css class bottom-border is here:

```
 .item[no-lines].bottom-border { 
        border-bottom: 1px solid map-get($colors, light); 
    }

```
[competizione.zip](https://github.com/GerritErpenstein/ionic2-custom-icons/files/1477944/competizione.zip)

**Comment by GerritErpenstein** [comment]
Alright, thanks for the additional info! I will look into it tomorrow.

**Comment by GerritErpenstein** [comment]
I have tested your code and the icons look good to me:
![screenshot_20171117_200927](https://user-images.githubusercontent.com/9967761/32964388-60c4b5ec-cbd3-11e7-85e9-c42b1f16dff6.png)

Can you please provide me the app or a stripped down version? If you don't want to share it with the world, send it via e-mail: gerrit.erpenstein.dev@gmail.com

**Comment by marcogrieco** [comment]
I have solved with two css classes

```
.iconText{
    display: inline-block;
    vertical-align: middle;
  }

  .iconImage {
    display: inline-block;
    font-size: 25px;    
    vertical-align: middle;
   }
```
The item in the list is 

```
<ion-item no-lines class="bottom-border" menuClose *ngFor="let p of pages" (click)="openPage(p)">
        <custom-icon class="iconImage" set="myIcons" name="{{p.icon}}" margin-right item-start></custom-icon>
        <span class="iconText">{{p.title | translate}}</span>
      </ion-item> 
```

Thanks

**Comment by GerritErpenstein** [comment]
I'm glad you solved it. Thanks for the feedback.
