### ISSUE TITLE
Icons not displaying on tabs

### ISSUE THREAD

**Issue by dayaki** [GerritErpenstein/ionic2-custom-icons#30]
Icons working perfectly on other pages of my app but its not displaying on the tabs, this is my code:

`<ion-tabs class="tabs-icon-text">`
  `<ion-tab [root]="tab1Root" tabTitle="Home" tabIcon="home"></ion-tab>`
  `<ion-tab [root]="tab2Root" tabTitle="About" tabIcon="information-circle"></ion-tab>`
  `<ion-tab customIconSet="hub" customIconName="niben"></ion-tab>`
  `<ion-tab [root]="tab3Root" tabTitle="Info" tabIcon="contact"></ion-tab>`
  `<ion-tab [root]="tab3Root" tabTitle="Contact" tabIcon="contacts"></ion-tab>`
`</ion-tabs>`

I also replace `customIconName` with icon name that is working on other pages but still it won't display.

My ionic info:
ionic (Ionic CLI) : 3.19.0
@ionic/app-scripts : 3.1.2
ionic-angular 3.9.2

**Comment by GerritErpenstein** [comment]
Hi @dayaki!
What happens if you add a tab root with the `root` property to the third tab? Could you also please test what happens if you also add the `tabTitle` property?
Are you using the latest version of `ionic2-custom-icons` (version `0.5.1`)?

**Comment by dayaki** [comment]
I tried both, this is my code `<ion-tab customIconSet="hub" customIconName="niben" [root]="tab2Root" tabTitle="Niben"></ion-tab>`

this is what i get, and yes am using version 0.5.1

![sc](https://user-images.githubusercontent.com/815619/33162659-fe6d8732-d02a-11e7-8631-67d3739d9976.jpg)

**Comment by GerritErpenstein** [comment]
I'm unable to reproduce this error but let's see if we can narrow down the problem.

Can you please run your app with `ionic serve` and debug it in Chrome or Chromium? Select the tab button DOM element and check the `<custom-icon>` is rendered correctly. See the following example screenshot for reference: 
![screenshot_20171126_170221](https://user-images.githubusercontent.com/9967761/33241876-1e28eed8-d2cc-11e7-9b5e-1c937956ee04.png)
The relevant DOM element for the tab button should look something lilke this:
```html
<a class="tab-button has-title disable-hover has-icon" href="#" role="tab" ...>
   <custom-icon class="tab-button-icon md icon-square set-test inactive"></custom-icon>
   ...
</a>
```
Can you please also check the console output in Chrome whether there are any error messages.

If you are unsure how to run Chrome in debug mode you can also send me a stripped down version of your app that allows me to reproduce the problem. You can attach it here or send it via e-mail to me: gerrit.erpenstein.dev@gmail.com.

**Comment by HindHesham** [comment]
i'v the same problem and this my console log 
![screenshot from 2018-02-06 06-44-17](https://user-images.githubusercontent.com/25655253/35842176-2fe62a08-0b09-11e8-99f1-5bd29d87082f.png)

**Comment by GerritErpenstein** [comment]
Hi @HindHesham,
thanks for your feedback!
Do you see any error message on the 'console' tab in the chrome debug window?
As mentioned in the previous message, it would be much easier for me to fix the problem if you can provide a minimal sample app.

**Comment by dayaki** [comment]
@GerritErpenstein Did a fresh installation of ionic and custom-icons, still having same issue. Should I host the sample app on github ??

**Comment by dayaki** [comment]
@HindHesham @GerritErpenstein  I got it working by importing **IonicPageModule** into my tabs.module.ts. Give it a try.

**Comment by GerritErpenstein** [comment]
Create a GH repo, upload a zip here or send it via e-mail to gerrit.erpenstein.dev@gmail.com ... just as you like. :smiley:

**Comment by GerritErpenstein** [comment]
Ah, I think I might understand the problem now.
Do you use lazy loading?

**Comment by dayaki** [comment]
Yes, am using lazy loading

**Comment by HindHesham** [comment]
Hi Mr.Gerrit,
thanks for your reply and i'm very sorry for i can't be available before
now to sending reply to you.

Your plugin is working well, my problem with the images i'v used but i
fixed it.
Thanks for your efforts.

**Comment by GerritErpenstein** [comment]
@dayaki I'll add a tab page with lazy loading to the example app. I hope this clears things up.
@HindHesham I'm glad you figured it out. :smiley: 
Thanks to both of you for giving feedback!

**Comment by dayaki** [comment]
Thanks for this awesome package.
