### ISSUE TITLE
Wrong Image Conversion 

### ISSUE THREAD

**Issue by marcogrieco** [GerritErpenstein/ionic2-custom-icons#33]
Hi,
i'm using this fantastic plugin to use svg image in my Ionic App but i'm having a problem. When i convert a colored image, the result is a wrong image.

![immagine](https://user-images.githubusercontent.com/26677763/35269101-59f790fe-002b-11e8-8f76-9407d939f2a9.png)

The original svg image is here.

[a.zip](https://github.com/GerritErpenstein/ionic2-custom-icons/files/1655340/a.zip)

Which is the problem?

Thanks in advance.

**Comment by GerritErpenstein** [comment]
Hi @marcogrieco,

your SVG contains a shape above another shape. During conversion to font icons, effectively all layered shapes get converted to a single shape as the color information is lost.
In your case the "A" is merged into the square. What you can do is creating the difference between the two shapes. That means the "A" is cut out of the square.
See the attached ZIP for an example.

[a_modified.zip](https://github.com/GerritErpenstein/ionic2-custom-icons/files/1657047/a_modified.zip)
