### ISSUE TITLE
Fooling around with the tabbar

### ISSUE THREAD

**Issue by ThorvaldAagaard** [GerritErpenstein/ionic2-custom-icons#34]
I would like to change the icon in the tabbar for the tab selected, and I have found some descriptions of how to do that on the web, but for some reason if I use ionic2-custom-icons, it looks like the DOM-tree is different than expected

My DOM-tree looks like this
![image](https://user-images.githubusercontent.com/10560652/35536839-5b08888c-0548-11e8-8fba-e34e09a610b4.png)
and what is interesting is the ng-reflect-name that the suggested solution is using to replace the image

```
    .tabs-ios {
       a[aria-selected=true] {
        .tab-button-icon[ng-reflect-name=location], .tab-button-icon[aria-label=location] {
            background-image: url(../assets/TabIcons/Icon-Fill-Green-Location@2x.png);
            background-size: 30px;
          }
        }
      }
```

If using one of the normal ionicicons ng-reflect-name will have the same name as the icon.

But what I really is interested in is being able to set to different icons, but I guess that is something I have to discuss with the Ionic team

**Comment by GerritErpenstein** [comment]
Hi @ThorvaldAagaard,
thanks for your message. I will take a look at it by the weekend.

**Comment by GerritErpenstein** [comment]
To my knowledge, Angular adds `ng-reflect-X` attributes for debugging purposes, where `X` is a input binding name.
The reason the `ng-reflect` attribute isn't generated for custom tab icons is, that the icons are programmatically added to the DOM as Ionic's extensibility is limited for this use case.

I don't see a reason that you use a custom icon if you replace it anyways. Other than that, I don't think it is good practice to rely on debugging facilities. But what you can do is using another CSS selector than `ng-reflect-` that distinctly selects the desired DOM element.

**Comment by ThorvaldAagaard** [comment]
You are probably right, but  my issue is that the designer want different icons when the tab is selected, and there is really no other way, than replacing the image in css as far as I can see.

![image](https://user-images.githubusercontent.com/10560652/35769749-0ca70d78-0910-11e8-9ea1-b4e709d7e47c.png)

![image](https://user-images.githubusercontent.com/10560652/35769757-2289ffb0-0910-11e8-8e5c-ed493650ae9e.png)

Currently I ended up manipulating the DOM for the user icon, but is looking for a way to have 2 different custom icons for a tab. 

But as this is outside the scope of custom-icons you are welcome to close this
