### ISSUE TITLE
Ionic build change, again...

### ISSUE THREAD

**Issue by sagivf** [GerritErpenstein/ionic2-custom-icons#5]
@GerritErpenstein I seriously feel your pain, but it looks like it's happened again...
http://blog.ionic.io/ionic-build-process-updates/

It says you can keep using roolup but:

1) Haven't tried upgrading so who knows if it works...
2) Never a good idea to steer away from the main development route.
3) I know you had a webpack option before, perhaps you  can support both.

Thanks again for your hard work and take your time, who knows what's in store 😄

**Comment by GerritErpenstein** [comment]
Hey @sagivf ! Thanks for the heads up!
I didn't have much time to take a look at the changes yet, but it seems like they only affect the bundling process (Rollup -> Webpack 2). So hopefully not much work needs to be put into this to get the library working with Webpack.
Switching central components like the build process tools means a lot of work for everybody involved, but generally I think trying new and promising ideas lead to to much better product. Therefore I'm fine with the decisions the Ionic Team makes. They are doing a really great job and I really appreciate the fact they are keeping their development process so open and comprehensible.
Give me a few hours or days to adapt the changes... :wink:

**Comment by GerritErpenstein** [comment]
Luckily the library needs no modifications to work with the new build process of `@ionic/app-scripts`.
Nevertheless I have updated the dependencies, published a new version (0.3.1) and updated the example app.
